# Generated by Django 2.2.14 on 2020-07-11 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=30, null=True)),
                ('text', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images')),
                ('icon', models.CharField(max_length=1000)),
                ('good', models.IntegerField(blank=True, default=0, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SecredMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('yourname', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=30, null=True)),
                ('text', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('icon', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersend', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=30, null=True)),
                ('text', models.CharField(max_length=1000)),
                ('icon', models.CharField(max_length=1000)),
                ('chatmessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.ChatMessage')),
            ],
        ),
    ]
