# Generated by Django 2.2.14 on 2020-07-11 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=30, null=True)),
                ('text', models.CharField(max_length=1000)),
                ('icon', models.CharField(max_length=1000)),
                ('chatmessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.ChatMessage')),
            ],
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
