version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    #working_directory: ~/project/chatapp 
    steps:
      - checkout
    #        path: ~/project

      - run: cd chatapp; ls -la; pwd;

      - restore_cache:
          keys:
          - chatapp-{{ checksum "package.json }}
          - chatapp-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: chatapp-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: |
              cd chatapp
              npm test

  django:
    docker:
      - image: circleci/python:3.6
      - image: circleci/postgres:9.6.5-alpine-ram
        auth:
          username: postgres
          password: $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_USER: postgres
    steps:
      - checkout

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            cd ..
            pwd
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py test
      - store_artifacts:
          path: /bin/test
          destination: test


workflows:
  version: 2
  sample_workflow:
    jobs:
      - build
      - django:
          requires:
            - build